#version: '3.1'

services:

  # Main MongoDB Node
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --bind_ip_all --replSet "${REPLSET_NAME}" --keyFile ${MONGO_KEYFILE_PATH}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-keyfile:${MONGO_KEYFILE_PATH}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"  # Main MongoDB exposed port

  # Mongo Express UI
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/
    depends_on:
      - mongo

  # Hidden MongoDB Node for Voting
  mongo-hidden:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --bind_ip_all --replSet "${REPLSET_NAME}" --keyFile ${MONGO_KEYFILE_PATH}
    volumes:
      - mongodb_hidden_data:/data/db
      - ./mongo-keyfile:${MONGO_KEYFILE_PATH}
    ports:
      - "${HIDDEN_PORT}:${MONGO_PORT}"  # Expose on a different port for the hidden member

volumes:
  mongodb_data:
  mongodb_hidden_data:
